#!/usr/bin/bash
set -e

file="$HOME/repos/github.com/robbiestoffel/dot/scripts/$1"
if test -e "$file"; then
	echo "Watchout! You already have a script titled $1."
	echo "It is located in $file"
	exit 1
fi
touch "$file"
chmod u+x "$file"
echo -e "#!$(which bash)\nset -e" >> "$file"
ln -sf "$file" "$HOME/.local/bin/$1"
exec vim "$file"
