#!/usr/bin/bash
set -e

file="$PWD/$1"
if test -e "$file"; then
	echo "Watchout! There is already a $1 here."
	exit 1
fi
touch "$file"
chmod u+x "$file"
echo -e "#!$(which perl)\nuse strict;\nuse warnings;" >> "$file"
exec vim "$file"

